### ISSUE TITLE
how to input suite or not suited card?

### ISSUE THREAD

**Issue by jeremy-linchao** [bupticybee/TexasHoldemSolverJava#21] opened 2021-08-04 03:45 UTC

**Comment by bupticybee** [comment] 2021-08-04 04:03
<img width="122" alt="截屏2021-08-04 下午12 02 17" src="https://user-images.githubusercontent.com/9393610/128120348-3427a703-122c-460a-9be2-7214c46518c8.png">

Take AK as an example.

suited AK are described as Aks, unsuited are Ako, it's basically the same defination as piosolver.

**Comment by jeremy-linchao** [comment] 2021-08-04 06:18
thanks

**Comment by bupticybee** [comment] 2021-08-04 07:04
Closing because the problem is solved.

**Closed by bupticybee** 2021-08-04 07:04 UTC
