### ISSUE TITLE
`output_strategy.json` not generated?

### ISSUE THREAD

**Issue by battermann** [bupticybee/TexasHoldemSolverJava#14] opened 2021-04-23 19:21 UTC
Hey,
first, this is an awesome program!
Maybe this is more a question than an issue, in the description it says the `output_strategy.json` is generated after solving, but it is either not or I don't know where it is located.
I am using macOS, and I am happy to provide all the information you need.
Thanks

**Comment by bupticybee** [comment] 2021-04-24 08:34
oh you have to modify the output directory in the script first

**Comment by bupticybee** [comment] 2021-04-24 08:38
by default it's generated in "resources/outputs/outputs_strategy.json"

**Comment by battermann** [comment] 2021-04-24 09:13
That works if I start the program from the command line.
However, when I start the GUI no `outputs_strategy.json` file is generated.
There is one in `resources/outputs/` but that contains the result of the default configuration and doesn't change when I run a new solve.

**Comment by bupticybee** [comment] 2021-04-25 14:24
> That works if I start the program from the command line.
> However, when I start the GUI no `outputs_strategy.json` file is generated.
> There is one in `resources/outputs/` but that contains the result of the default configuration and doesn't change when I run a new solve.

that's right.  gui version don't support dump strategy to disk

**Comment by battermann** [comment] 2021-04-26 21:10
Got it. Thanks!

**Comment by bupticybee** [comment] 2021-04-27 06:48
Closing because the problem is solved.

**Closed by bupticybee** 2021-04-27 06:48 UTC
